### ISSUE TITLE
No backups were found to restore the database to the point in time

### ISSUE THREAD

**Issue by chrislaf** [geeklearningio/gl-vsts-tasks-azure#44]
For this year the task has been running daily with out errors but over the last two month this error has started happening more and more. Now the error happens 99% of the time.

1200003: No backups were found to restore the database to the point in time 9/9/2019 12:03:56 AM (UTC). Please contact support to restore the database.

The Azure database does not have a backup at that point in time. If I do a manual restore via Azure Portal the latest Restore Point available is about 5 min earlier.

Can the task get the latest backup that is available  - not the backup at the exact time the task is run?

**Comment by sandorfr** [comment]
Sorry couldn't look at this earlier. the current process is definitely flaky :( sorry about that.
I guess we need to call `https://docs.microsoft.com/en-us/powershell/module/azurerm.sql/get-azurermsqldatabaserestorepoints?view=azurermps-6.13.0` instead of a harcoded window. 
I'll try to get that out soon unless @asiffermann volunteers :)

**Comment by chrislaf** [comment]
Just to add to the current process - 
The Database is deleted before the backup is run.
If I get the error "No backups were found to restore the database to the point in time" My existing database has been deleted.

Could the delete happen after a relevant backup is found.
